### PR TITLE
make circles as big as AA range

### PR DESCRIPTION
**Pull request by myo**

### CODE REVIEW

**Comment by botkalista** [comment]
circle3D is not used, it is there only for debug purposes.
The render itself has a function to calculate the circle points inside [script.js](https://github.com/botkalista/ayaya-league-external/blob/a375bff025b9b500e6ae54975b7cc05e2a0c1e9b/static/script.js#L81)

**Comment by myo** [comment]
Oh, right, lol. Was just going through the source and this didn't seem quite right. Should you be calculating it twice though? Even though it takes ~2ms per loop for me, it still looks pretty heavy.

**Comment by botkalista** [comment]
I'll remove the first calculation as soon as i have a consistent draw (need champs bounding boxes)

**Comment by myo** [comment]
You can use this for bounding radius:
[UnitData.json.zip](https://github.com/botkalista/ayaya-league-external/files/9277619/UnitData.json.zip)

Also I made a (mostly accurate) MissileDB with (almost) only dodgeable spells:
[MissileData.json.zip](https://github.com/botkalista/ayaya-league-external/files/9277617/MissileData.json.zip)

Both up to date (patch 12.14), both using data from communitydragon

**Comment by myo** [comment]
updated above to use your format, added championName & championNameLowerCase fields for each spell @botkalista 
[MissileDb.json.zip](https://github.com/botkalista/ayaya-league-external/files/9277686/MissileDb.json.zip)

**Comment by botkalista** [comment]
@myo thx, much appreciated

**Pull request closed without merging**
